const defaultList = [
    {
        text: 'Card One',
        name: '党党',
        image: require('./img/swiper-1.png'),
        interests: ['Cooking','Party','Meeting'],
        class: 2018,
        major: ['Marketing'],
        numLiveWith: 2,
        preferArea: ['Fenway', 'Boston'],
        priceRange: [2000, 3000],
        smoke: false,
        pet: false,
        likeParty: true,
        wechat: 'dangdangkarl'
    },
    {
        text: 'Card One',
        name: '冯老师 ',
        image: require('./img/swiper-2.png'),
        interests: ['Soccer','Beer','Guitar'],
        class: 2020,
        major: ['Biology'],
        numLiveWith: 2,
        preferArea: ['Allston', 'Brookline'],
        priceRange: [1000,1200],
        smoke: true,
        pet: false,
        wechat: 'stevennn'
    },
    {
        text: 'Card One',
        name: 'Alexa',
        image: require('./img/swiper-3.png'),
        interests: ['Basketball','Game'],
        class: 2018,
        major: ['Biology'],
        numLiveWith: 2,
        preferArea: ['Allston', 'Brookline'],
        priceRange: [1400,1600],
        smoke: false,
        pet: false,
        wechat: 'amelieee96'
    },
    {
        text: 'Card One',
        name: '仙仙 ',
        image: require('./img/swiper-4.png'),
        interests: ['Soccer','Beer','Guitar'],
        class: 2020,
        major: ['Biology'],
        numLiveWith: 2,
        preferArea: ['Allston', 'Brookline'],
        priceRange: [1000,1200],
        smoke: true,
        pet: false,
        wechat: 'stevennn'
    },
    {
      text: 'Card One',
        name: '肉松',
        image: require('./img/swiper-7.png'),
        interests: ['OW','Icecream','Cake'],
        class: 2018,
        major: ['Psychology'],
        numLiveWith: 2,
        preferArea: ['Allston', 'Brookline'],
        priceRange: [1400,1600],
        smoke: false,
        pet: true,
        wechat: 'MRMX_DoNuts'
    },
    {
      text: 'Card One',
        name: 'May',
        image: require('./img/swiper-8.png'),
        interests: ['pretty','Alcohol','419'],
        class: 2021,
        major: ['Social interaction'],
        numLiveWith: 1,
        preferArea: ['Queen', 'Uptown'],
        priceRange: [3000,4000],
        smoke: true,
        pet: false,
        wechat: 'GoNuts'
    },
    {
      text: 'Card One',
        name: 'Sibo',
        image: require('./img/swiper-9.png'),
        interests: ['Coding','Wow'],
        class: 2018,
        major: ['Computer Science'],
        numLiveWith: 1,
        preferArea: ['Boston', 'Brookline'],
        priceRange: [800,1000],
        smoke: false,
        pet: false,
        wechat: 'arfa211243'
    },
    {
      text: 'Card One',
        name: '王翌',
        image: require('./img/swiper-10.png'),
        interests: ['Swimming','Eating'],
        class: 2019,
        major: ['Mathematics'],
        numLiveWith: 1,
        preferArea: ['Boston', 'Brookline'],
        priceRange: [1200,1600],
        smoke: false,
        pet: true,
        wechat: 'fafs15738'
    },
    {
      text: 'Card One',
        name: 'L',
        image: require('./img/swiper-11.png'),
        interests: ['Coding','Photography', 'Piano'],
        class: 2018,
        major: ['Mathematics', 'Computer Science'],
        numLiveWith: 3,
        preferArea: ['Allston', 'Brookline'],
        priceRange: [1000,1300],
        smoke: false,
        pet: true,
        wechat: 'Cardinal'
    },
];

export default defaultList
